<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Using Include="System.Collections.ObjectModel" />
    <Using Include="System.Diagnostics" />
    <Using Include="System.Globalization" />
    <Using Include="System.Reflection" />
    <Using Include="System.Runtime.InteropServices" />
    <Using Include="System.Runtime.Serialization" />
    <Using Include="System.Security" />
    <Using Include="System.Security.Cryptography" />
    <Using Include="System.Text" />
    <Using Include="System.Xml" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.ItemsRepeater" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="FluentIcons.Avalonia" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="ScottPlot.Avalonia" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))'" />
    <PackageReference Include="StyleCop.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Woohoo.Platform.MacOS" />
    <PackageReference Include="Woohoo.Platform.Windows" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Woohoo.Audio.Core\Woohoo.Audio.Core.csproj" />
    <ProjectReference Include="..\Woohoo.Audio.Playback.Sdl3\Woohoo.Audio.Playback.Sdl3.csproj" />
    <ProjectReference Include="..\Woohoo.Audio.Services.Impl\Woohoo.Audio.Services.Impl.csproj" />
    <ProjectReference Include="..\Woohoo.Audio.Services\Woohoo.Audio.Services.csproj" />
    <ProjectReference Include="..\Woohoo.Discue.Shared.Avalonia\Woohoo.Discue.Shared.Avalonia.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localized.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Localized.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localized.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Localized.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
