<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <NeutralLanguage>en</NeutralLanguage>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <TreatWarningsAsErrors Condition="'$(TreatWarningsAsErrors)' == ''">true</TreatWarningsAsErrors>
    <NoWarn>CS1591;SA1600;SA0001;IDE0290</NoWarn>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <SignAssembly>false</SignAssembly>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
  </PropertyGroup>

  <PropertyGroup>
    <Company>Hugues Valois</Company>
    <Copyright>Copyright (c) Hugues Valois 2025-2026</Copyright>
    <Product>Discue</Product>
    <Version>0.14.0.0</Version>
    <FileVersion>0.14.0.0</FileVersion>
    <ApplicationVersion>0.14.0</ApplicationVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- See also https://github.com/dotnet/efcore/issues/38257 -->
    <!-- TODO: Remove this when Microsoft.EntityFrameworkCore.Sqlite is updated -->
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-2m69-gcr7-jv3q" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)Common\stylecop.json" Link="stylecop.json" />
  </ItemGroup>

</Project>