<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.1.1" />
    <PackageVersion Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageVersion Include="Avalonia.Skia" Version="12.1.1" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageVersion Include="AwesomeAssertions" Version="9.5.0" />
    <PackageVersion Include="AwesomeAssertions.Analyzers" Version="9.0.8" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="CommunityToolkit.WinUI.Animations" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Collections" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.Sizers" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Converters" Version="8.2.251219" />
    <PackageVersion Include="Consolonia" Version="12.0.3.7" />
    <PackageVersion Include="Consolonia.Fonts" Version="12.0.3.7" />
    <PackageVersion Include="Consolonia.ManagedWindows" Version="12.0.3.7" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="coverlet.MTP" Version="10.0.1" />
    <PackageVersion Include="Dapper" Version="2.1.79" />
    <PackageVersion Include="Dapper.AOT" Version="1.0.52" />
    <PackageVersion Include="FftSharp" Version="2.2.0" />
    <PackageVersion Include="FluentIcons.Avalonia" Version="2.1.333" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Graphics.Win2D" Version="1.4.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="Microsoft.Windows.CsWin32" Version="0.3.298" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools.WinApp" Version="0.5.0" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
    <PackageVersion Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="3.0.1" />
    <PackageVersion Include="Microsoft.XmlSerializer.Generator" Version="10.0.9" />
    <PackageVersion Include="ppy.SDL3-CS" Version="2026.722.0" />
    <PackageVersion Include="RichardSzalay.MockHttp" Version="7.0.0" />
    <PackageVersion Include="ScottPlot.Avalonia" Version="5.1.59" />
    <PackageVersion Include="Serilog" Version="4.4.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="3.119.4-preview.1.1" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    <PackageVersion Include="System.CommandLine" Version="2.0.10" />
    <PackageVersion Include="WinUIEx" Version="2.9.2" />
    <PackageVersion Include="Woohoo.Platform.MacOS" Version="0.1.0" />
    <PackageVersion Include="Woohoo.Platform.Windows" Version="0.1.0" />
    <PackageVersion Include="Woohoo.Security.Cryptography" Version="0.5.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="xunit.v3" Version="3.2.0" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />
    <PackageVersion Include="ZstdSharp.Port" Version="0.8.8" />
  </ItemGroup>
</Project>