name: Build All

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-macos-avalonia:
    uses: ./.github/workflows/generic-build-mac.yml
    with:
      tag-name: ${{ github.ref_name }}
      icon-path: src/Woohoo.Discue.Avalonia/Assets/app-logo.png
      project-file-path: Woohoo.Discue.Avalonia.Desktop/Woohoo.Discue.Avalonia.Desktop.csproj
      app-short-name: Discue
      app-display-name: 'Discue'
      app-executable-name: Woohoo.Discue.Avalonia.Desktop
      bundle-identifier: com.huguesvalois.discue
    secrets: inherit

  build-windows-avalonia:
    uses: ./.github/workflows/generic-build-windows.yml
    with:
      tag-name: ${{ github.ref_name }}
      project-file-path: Woohoo.Discue.Avalonia.Desktop/Woohoo.Discue.Avalonia.Desktop.csproj
      app-executable-name: Woohoo.Discue.Avalonia.Desktop
    secrets: inherit

  build-windows-cli:
    uses: ./.github/workflows/generic-build-windows.yml
    with:
      tag-name: ${{ github.ref_name }}
      project-file-path: Woohoo.Discue.Cli/Woohoo.Discue.Cli.csproj
      app-executable-name: Woohoo.Discue.Cli
    secrets: inherit

  build-windows-tui:
    uses: ./.github/workflows/generic-build-windows.yml
    with:
      tag-name: ${{ github.ref_name }}
      project-file-path: Woohoo.Discue.Consolonia/Woohoo.Discue.Consolonia.csproj
      app-executable-name: Woohoo.Discue.Consolonia
    secrets: inherit

  build-linux-avalonia:
    uses: ./.github/workflows/generic-build-linux.yml
    with:
      tag-name: ${{ github.ref_name }}
      project-file-path: Woohoo.Discue.Avalonia.Desktop/Woohoo.Discue.Avalonia.Desktop.csproj
      app-executable-name: Woohoo.Discue.Avalonia.Desktop
    secrets: inherit

  build-linux-cli:
    uses: ./.github/workflows/generic-build-linux.yml
    with:
      tag-name: ${{ github.ref_name }}
      project-file-path: Woohoo.Discue.Cli/Woohoo.Discue.Cli.csproj
      app-executable-name: Woohoo.Discue.Cli
    secrets: inherit

  build-linux-tui:
    uses: ./.github/workflows/generic-build-linux.yml
    with:
      tag-name: ${{ github.ref_name }}
      project-file-path: Woohoo.Discue.Consolonia/Woohoo.Discue.Consolonia.csproj
      app-executable-name: Woohoo.Discue.Consolonia
    secrets: inherit
